addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"     % "3.9.5")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"          % "2.0.2")
addSbtPlugin("com.github.gseitz"                 % "sbt-release"      % "1.0.13")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.2")
addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"     % "0.11.0")
